name: CI

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  check_workflows:
    name: Check workflows
    uses: $/.github/workflows/check_workflows.yml
    permissions:
      security-events: write

  update-csaf-metadata:
    name: Update CSAF Metadata
    permissions:
      contents: write
      pull-requests: write
    uses: $/.github/workflows/update_csaf_metadata.yml