name: PR

on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
      
permissions: {}

jobs:
  check-csaf-schema:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    uses: $/.github/workflows/check_csaf_schema.yml

