name: PR

on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
      
permissions: {}

jobs:
  update-csaf-metadata:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/update_csaf_metadata.yml
